# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mbblock_i/mbblock_i.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i || ORIG_REF_NAME==mbblock_i} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_microblaze_0_0/mbblock_i_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_microblaze_0_0 || ORIG_REF_NAME==mbblock_i_microblaze_0_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_dlmb_v10_0/mbblock_i_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_dlmb_v10_0 || ORIG_REF_NAME==mbblock_i_dlmb_v10_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_ilmb_v10_0/mbblock_i_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_ilmb_v10_0 || ORIG_REF_NAME==mbblock_i_ilmb_v10_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_dlmb_bram_if_cntlr_0/mbblock_i_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbblock_i_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_ilmb_bram_if_cntlr_0/mbblock_i_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbblock_i_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_lmb_bram_0/mbblock_i_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_lmb_bram_0 || ORIG_REF_NAME==mbblock_i_lmb_bram_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_xbar_0/mbblock_i_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_xbar_0 || ORIG_REF_NAME==mbblock_i_xbar_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_microblaze_0_axi_periph_0/mbblock_i_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mbblock_i_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_microblaze_0_axi_intc_0/mbblock_i_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mbblock_i_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_microblaze_0_xlconcat_0/mbblock_i_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mbblock_i_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_mdm_1_0/mbblock_i_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_mdm_1_0 || ORIG_REF_NAME==mbblock_i_mdm_1_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_clk_wiz_1_0/mbblock_i_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_clk_wiz_1_0 || ORIG_REF_NAME==mbblock_i_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_rst_clk_wiz_1_100M_0/mbblock_i_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mbblock_i_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_uartlite_0_0/mbblock_i_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_uartlite_0_0 || ORIG_REF_NAME==mbblock_i_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_0/mbblock_i_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_0 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_1/mbblock_i_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_1 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_quad_spi_0_0/mbblock_i_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_quad_spi_0_0 || ORIG_REF_NAME==mbblock_i_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_timer_0_0/mbblock_i_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_timer_0_0 || ORIG_REF_NAME==mbblock_i_axi_timer_0_0} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_2/mbblock_i_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_2 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_3/mbblock_i_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_3 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_4/mbblock_i_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_4 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_5/mbblock_i_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_5 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_5} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_axi_gpio_0_6/mbblock_i_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_axi_gpio_0_6 || ORIG_REF_NAME==mbblock_i_axi_gpio_0_6} -quiet] -quiet

# IP: bd/mbblock_i/ip/mbblock_i_hdmi_text_controller_0_0/mbblock_i_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblock_i_hdmi_text_controller_0_0 || ORIG_REF_NAME==mbblock_i_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Chess/ChessSpartan7/ChessSpartan7.gen/sources_1/bd/mbblock_i/mbblock_i_ooc.xdc
