# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Chess/ChessSpartan7/ChessSpartan7.srcs/sources_1/bd/mbblock_i/ip/mbblock_i_xbar_0/mbblock_i_xbar_0.xci
# IP: The module: 'mbblock_i_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Chess/ChessSpartan7/ChessSpartan7.gen/sources_1/bd/mbblock_i/ip/mbblock_i_xbar_0/mbblock_i_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblock_i_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Chess/ChessSpartan7/ChessSpartan7.srcs/sources_1/bd/mbblock_i/ip/mbblock_i_xbar_0/mbblock_i_xbar_0.xci
# IP: The module: 'mbblock_i_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Chess/ChessSpartan7/ChessSpartan7.gen/sources_1/bd/mbblock_i/ip/mbblock_i_xbar_0/mbblock_i_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblock_i_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
